# Generated by Django 4.2.8 on 2023-12-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmotiArt_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
