# Generated by Django 4.2.8 on 2023-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rnn_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="MyImage",
        ),
    ]
