# Generated by Django 4.2.8 on 2023-12-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rnn_app", "0002_myimagemodel_delete_myimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myimagemodel",
            name="description",
        ),
    ]
